name: heic_to_png_jpg
description: A Flutter package to convert HEIC images to JPG or PNG format on both web and mobile platforms.
version: 0.0.3
homepage: https://github.com/IbrahimElmourchidi/heic_to_png_jpg
repository: https://github.com/IbrahimElmourchidi/heic_to_png_jpg

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.5
  image: ^4.0.15
  heif_converter: ^1.0.1
  path_provider: ^2.0.14
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

platforms:
  android:
  ios:
  web:
